### ISSUE TITLE
Feature request - Add spoiler log parsing.

### ISSUE THREAD

**Issue by ghost** [sg4e/MaikaTracker#45]
Some example spoiler logs can be found at https://www.aexoden.com/ff4fe-spoiler/FF4FE.bAAMILLmIALAFt1AqLg.15MINUTES1.txt and https://www.aexoden.com/ff4fe-spoiler/FF4FE.bAAMILLmIALAFt1AqLg.15MINUTES2.txt

**Comment by CaitSith2** [comment]
@Kirito9156 You can use the build at https://github.com/CaitSith2/MaikaTracker/releases for the time being.  spoiler log parsing has been fully implemented.

**Comment by sg4e** [comment]
Added in 5bb287f
